### ISSUE TITLE
3주차 과제 : 미세먼지 데이터 웹 페이지로 조회하기

### ISSUE THREAD

**Issue by jeonghi** [kmu-koss/22_summer_bootcamp#1]
< 과제 제출 방법 >

* 과제는 일요일 밤 10시까지 개인 github repo에 올린후, Issue 에 댓글로 깃허브 주소를 남깁니다.

* 과제 제출물은 소스코드와 구현결과 촬영 영상, 과제 보고서 ( README.md 에 작성 ) 총 3가지입니다.

* 과제 보고서에 들어갈 내용은
과제 구현 소스 코드 line by line 으로 설명

* 구현 결과 영상은 스냅샷 툴을 이용해 스냅샷으로 촬영하고 github repo 의 README.md 에 첨부합니다.

**Comment by mrpc2003** [comment]
**3주차 / 4주차 과제를 통합해서 제출합니다**
[https://github.com/mrpc2003/koss_iot
](url)

**Comment by HeeNamgoong** [comment]
https://github.com/HeeNamgoong/Query_fine_dust_data_with-webpage_koss3week

**Comment by HeeNamgoong** [comment]
선우가 밖이라 못 올린다고 해서 대신 주소 올립니다.
https://github.com/woonsango/koss_iot_study

**Comment by bgw4399** [comment]
https://github.com/bgw4399/koss_bootcamp/blob/main/README.md

**Comment by overhyeon** [comment]
https://github.com/overhyeon/BootCamp_Assignment

**Comment by nnyouung** [comment]
https://github.com/nnyouung/koss_bootcamp
