### ISSUE TITLE
3주차 과제 질문 _ 라인 별 코드 설명에 관하여

### ISSUE THREAD

**Issue by mrpc2003** [kmu-koss/22_summer_bootcamp#13]
과제 중 과제 구현 코드를 라인별로 설명을 적어서 제출하는 과제가 있는데,
3주차 과제의 경우, 단일 파일로 된 프로그램이 아닌, 여러 파일로 나뉘어져서 동작을 하는 프로그램으로 완성을 했습니다.

이때, 과제 구현에서 중요한 역할을 하는 파일만 따로 설명을 해야하는건지,

과제를 하면서 만든 모든 파일의 코드에 대해서 설명을 해야하는건지 궁금합니다.

ps. 라벨로 질문을 선택하려고 해도 'none yet'으로 되어있어서 불가피하게 라벨 설정을 하지 못했습니다😢
![image](https://user-images.githubusercontent.com/74747291/183286613-8ee58f12-85e8-4415-a8bd-f39bff107849.png)

**Comment by jeonghi** [comment]
@mrpc2003 과제의 목적이 복습과 응용에 초점을 맞췄기 때문에, 가능하면 라인별 코드 설명을 적었으면 좋겠지만, 너무 비효율적일 경우 블록 단위로 설명해도 괜찮아요. 또, 3주차 과제의 핵심은 센서 데이터를 담기 위한 데이터베이스 모델링을 어떻게 구성했는지, 그리고 데이터베이스로부터 데이터를 쓰기/읽기를 할 수 있는지, 요청한 데이터를 적절하게 다뤄 시각적으로 사용자에게 나타낼 수 있는지 정도일 것 같아요. 본인의 주관적인 판단하에 핵심적인 부분을 뽑아보고 거기에 대해서만 설명해도 괜찮아요
